version: '3'
services:
  python3:
    restart: always
    build: .
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    container_name: 'jupyterlab_env'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    command: jupyter-lab --ip 0.0.0.0 --allow-root --NotebookApp.token=''
